tap "clojure/tools"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "autojump"
brew "git"
brew "gnupg"
brew "gradle"
brew "htop"
brew "jq"
brew "tig"
brew "watch"
brew "zsh", link: false
cask "mattermost"
cask "rar"
